### ISSUE TITLE
Probspace issues

### ISSUE THREAD

**Issue by kevindavisross** [hayate0304/Rsymbulate#10]
I've attached a pdf file with some tests. I've reviewed functionality but not the actual code. Here are a few issues/comments.

- How do you access results of particular repetitions?  For example, `sim(10)` and get the results of repetiton number 3?  In Python there is `get`; I don't think we specifically need get, but there should be some way to do it.  (What kind of object is results?)
- Is it possible to raise a [probability space to a power for i.i.d. draws](https://dlsun.github.io/symbulate/probspace.html#indep), e.g. with `%^%` (like `**` in Python)
- `size=inf` for BoxModel and `%^% inf` for probability spaces: can wait till later?
- `filter` functions appear to work properly to create subsets, but how to work with them, e.g. by finding `length`?

```{r}
P = Binomial(5, 0.5)
x = P %>% sim(10000)
length(x %>% filter_eq(3))
```

[TEST-ProbSpace.pdf](https://github.com/hayate0304/Rsymbulate/files/2322404/TEST-ProbSpace.pdf)

**Comment by hayate0304** [comment]
- Depends on how many `probSpace `is given, $results will be either a vector or a matrix. For example, for `BoxModel(1:4) %>% sim(10)` returns a vector, but `BoxModel(1:4, 3) %>% sim(10)` returns a matrix. `get `is reasonable, i can create one
- `filter `returns a `Results `object. I checked math.py and results.py and couldn't find a function `len()` for the `Results `object. Not sure how Python can use `len()` on `filter` to get the count. You can do `lenght((x %>% filter_eq(3))$results)` to get the count in R. I can create a `len()` method for nicer if you want.
- Can I assume the users won't do something like this in R 
![image](https://user-images.githubusercontent.com/23329938/44683008-d9c02800-a9f9-11e8-87f3-becb2eceb3a5.png)
