### ISSUE TITLE
Format print out of sims or apply

### ISSUE THREAD

**Issue by hayate0304** [hayate0304/Rsymbulate#11]
Do you prefer the sims print out flat like a vector like this 
![image](https://user-images.githubusercontent.com/23329938/44876161-1176dc00-ac55-11e8-8495-6139a707028d.png)
Or like a matrix
![image](https://user-images.githubusercontent.com/23329938/44876189-27849c80-ac55-11e8-9636-0a1d3856334d.png)

**Comment by kevindavisross** [comment]
In terms of display, I don't have a strong preference, but vertical display like a matrix would be consistent with Python.

What's more important are any implications that vector vs matrix has on other functionality.
