### ISSUE TITLE
apply() method has to be called as "apply.Results"

### ISSUE THREAD

**Issue by hayate0304** [hayate0304/Rsymbulate#2]
In R, if i create my generic mean for class "a", I can call mean() straight away and R search for the mean method of that class automatically thanks to UseMethod(). For some reason, if I implement my own apply() such as method apply in class Results and run it, R always assume I want to use the base apply() instead of finding the method apply for Results class. I googled but couldn't find any solution. So right now I have to run apply.Results all the time.

**Comment by dlsun** [comment]
Can we just give it a different name, like Apply?

**Comment by hayate0304** [comment]
Yes, that works
