### ISSUE TITLE
Using init.R to run all files right now

### ISSUE THREAD

**Issue by hayate0304** [hayate0304/Rsymbulate#3]
Hi,

I currently run files by running a init.R that source all my .R files. I researched about creating a package but somehow I feel it's complicated. I'm not sure if you want me to create a package now or not. I think I'll just work like this for now (without creating a package).

**Comment by kevindavisross** [comment]
My thought is that you should go ahead and set up the package now, but I'll defer to @dlsun

I've looked at some of what you have done so far, namely the examples related to the ProbSpace section of the getting started tutorial.  I think this is a good start.  Let me know when you think RV is in a good place to review.

**Comment by kevindavisross** [comment]
Also, your results.r file (and maybe others) still has a `setwd` command in it.

**Comment by hayate0304** [comment]
Okay, I'll remove that. I'm trying to create a package.
