### ISSUE TITLE
Tabulate: not working properly when an outcome is a tuple

### ISSUE THREAD

**Issue by kevindavisross** [hayate0304/Rsymbulate#4]
Example
```
P = BoxModel(1:4, size=2)
P %>% sim(10000) %>% tabulate()
```

`P %>% draw` correctly returns a pair of values, e.g. (3, 1).  Tabulate should summarize these pairs, e.g. (3,1) with count of 625.  However, the above code is returning a table of just the values 1:4, with each value occurring about 5000 times.  I don't know if this a problem just with tabulate, or a larger issue about results objects.

(By the way, I really like that the piping syntax `%>%` is implemented.)

**Comment by hayate0304** [comment]
I'm working on this. Taking me a lot of time but I think I almost figure out. (I just make my repo to become a package, `%>%` is still implemented). You can run devtools::install.github("hayate0304/Rsymbulate") and library(symbulate) to get it

**Comment by kevindavisross** [comment]
I haven't tested thoroughly, but here are a few comments.

- Thanks for creating the package.
- Please post in Github some .rmd files with documentation of tests you've run, like the probspace tutorial you did
- Tabulate: `normalize=TRUE` option gives error.  But `normalize=FALSE` does appear to work when outcomes are tuples now.
- The `Apply` issue seems to have been fixed; it appears to work with either scalar or vector values.
- `count` functions were working before, but they aren't now
- I tried a few things with `RV`.  It's off to a good start.
- Let me know when you think you have implemented all the functionality needed to complete the probspace and RV sections of the tutorial.  Or most of the functionality, with a status report of what's still left.

**Comment by hayate0304** [comment]
Can you give me examples that `count` doesn't work. Right now I don't have main `filter `or `count ` function. I only have those related to them like filter_eq, count_eq...
I'm stuck at the `plot()` for impulse. Since R doesn't have something line vlines function in Python. Currently working to create something like that and searching for new way.

**Comment by kevindavisross** [comment]
I tried 

```
P <- BoxModel(c(1,0), 5)
x = P %>% sim(10000) %>% Apply(sum)
count_eq(x, 2) / 10000 
```
and got `could not find function "count_eq"`

**Comment by hayate0304** [comment]
Okay, I just pushed a new version, can you test it again. I think have implemented all the functionality needed to complete the probspace tutorial. You can test the RV tutorial until Exercise 2.13 (just function related to those in the tutorial). `sd()` is `std()` and `var()` is `Var()`. I wasn't able to find a way to add a new plot to an existing plot (for the jitter impulse thing). I searched a lot, do you have any suggestions for that?

**Comment by hayate0304** [comment]
Hold on, I know the issue. I have different version from what I pushed

**Comment by kevindavisross** [comment]
Let's try to keep these issues on topic.  I'm going to close this one since the tabulate issue seems to be fixed, and then open some other ones.

@hayate0304 please make sure your latest version is in Github.  I just installed again, and I still am getting errors that `count_eq` cannot be found.
