### ISSUE TITLE
Apply: not working with non-array output

### ISSUE THREAD

**Issue by kevindavisross** [hayate0304/Rsymbulate#5]
Apply seems to work fine when outcomes are tuples; example
```
P = BoxModel(1:6, size=2)
P %>% sim(10000) %>% Apply(sum)
```

However, when an outcome is a single value Apply (and R apply) returns an error.  Example
```
P = BoxModel(1:6)
P %>% sim(10000) %>% Apply(log)
```
returns error 
`Error in apply(self$results, 1, fun) : dim(X) must have a positive length`

Maybe Apply needs to implement two cases, depending on if len(x)=1 or >1.

**Comment by hayate0304** [comment]
I fixed this one. You can pull and test this issue and the Tabulate() issue again.
