### ISSUE TITLE
Discussion about creating apply, var, sd ...

### ISSUE THREAD

**Issue by hayate0304** [hayate0304/Rsymbulate#6]
I can create those functions but if users load the package, those will mask the base:: apply, var, sd in R. And then if users want to use the base version, they need to specify base::apply. Right now I'm using Apply, Var, Sd. Let me know which way you prefer. (still not sure how only mean() function dispatch correctly)

**Comment by kevindavisross** [comment]
Let's adopt the convention that all SymbulateR functions will be capitalized, e.g. BoxModel, Sim, ProbabilitySpace, RV, Apply, Tabulate, Mean, Var, SD, Filter, Count, Cov, Corr, etc.  (Use UpperCamelCase for multiple words, like BoxModel.) This will yield consistency and also avoid issues with masking other R functions.  Sound reasonable?

**Comment by hayate0304** [comment]
Reasonable, I'll change them all soon

**Comment by hayate0304** [comment]
I got this to work normally with lower case
