### ISSUE TITLE
Plotting issues

### ISSUE THREAD

**Issue by kevindavisross** [hayate0304/Rsymbulate#8]
For now, focus on creating the following plots;

- [impulse plot](https://dlsun.github.io/symbulate/graphics.html#impulse) for discrete output, with the `normalize` option
- [histogram](https://dlsun.github.io/symbulate/graphics.html#hist) for continuous output, with the `normalize` and `bins` options
- [scatter plot](https://dlsun.github.io/symbulate/graphics.html#scatter) for multivariable output, with the `jitter` option (when you get there)

Please use `ggplot` because I think this will help when we add other plots later on.  For now, you do NOT need to work on overlaying multiple plots on the same graph.  However, you should be able to do this in `ggplot` just using `+`.

**Comment by hayate0304** [comment]
Okay, you can test these 3. Let me know if there are issues. My scatter plot only works for 2 RVs now. You can use `%&%` for joint RVs.
